# Generated by Django 4.2.7 on 2023-11-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=100),
        ),
    ]
