# Generated by Django 4.2.7 on 2023-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите в формате ДД.ММ.ГГГГ', null=True, verbose_name='Дата рождения'),
        ),
    ]
