# Generated by Django 4.2.7 on 2023-11-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=150, null=True),
        ),
    ]
