# Generated by Django 4.2.7 on 2023-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=100, verbose_name='Телефон'),
        ),
    ]
