# Generated by Django 4.2.7 on 2023-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_food', '0002_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Цена'),
        ),
    ]
