# Generated by Django 4.2.7 on 2023-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_food', '0003_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=5, verbose_name='Цена'),
        ),
    ]
