# Generated by Django 4.2.7 on 2023-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_food', '0004_food_pic_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
