# Generated by Django 4.2.7 on 2023-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_food', '0007_alter_food_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
